name: Generate 3D Contribution Profile

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate 3D contribution profile
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ProCodesWithPratap

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: Generate 3D contribution profile
          add: profile-3d-contrib/*.svg
